export const ADD_TODO = "ADD_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO_LIST = "UPDATE_TODO_LIST";
export const ADD_NEW_TODO_TO_LIST = "ADD_NEW_TODO_TO_LIST";

export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";